export {HomePage} from "./HomePage/HomePage"
export {ProductPage} from "./ProductPage/ProductPage"
export {LoginPage} from "./Auth/Login/LoginPage"
export {LogoutPage} from "./Auth/Logout/LogoutPage"
export {SignupPage} from "./Auth/Signup/SignupPage"
export {CartPage} from "./CartPage/CartPage"
export {WishlistPage} from "./WishlistPage/WishlistPage"
export {SingleProductPage} from "../pages/ProductPage/SingleProductPage/SingleProductPage"
